### ISSUE TITLE
APp built, please test

### ISSUE THREAD

**Issue by andreakoelzsch** [chei90/EMAC_Corridors#1]
Dear chei90, thanks a lot for this contribution to EMAC23! It is now built in the platform, please try out if it performs as you expect also there. All the best, Andrea (MoveApps)

**Comment by andreakoelzsch** [comment]
Please synchronise the name of the App with the title of the readme.md (Hotspots vs. Corridors) Thank you!

**Comment by chei90** [comment]
Hey andreakoelzsch,
I've updated the name. Unfortunately I've forgotten to set the flag for artifacts to true, so you've got an other request. 
Best regards

**Comment by andreakoelzsch** [comment]
new App version is built, please test and thanks a lot!

**Comment by andreakoelzsch** [comment]
@chei90 another App version is built, thanks!
