### ISSUE TITLE
html file is empty

### ISSUE THREAD

**Issue by andreakoelzsch** [chei90/EMAC_Corridors#2]
Hi chei90, Before sending the code challenge APps off for review, we are carefully looking over all the outputs again. We have recognised that the html file that your App is providing is empty. Please would you check how to solve this? I share a workflow on MoveApps with you, where you see the problem. Thanks for your help! Andrea

**Comment by andreakoelzsch** [comment]
maybe not important here, but I wanted to note that I do remember seeing a nice html map with white corridor blobs at some point of the App versions. Maybe the settings are not good for the fishers user case? Or did anything change with the second or third version of the App? Thanks!

**Comment by andreakoelzsch** [comment]
Hi again, I now see that there are some results in the html after all, but that the map is zoomed out so much, that one cannot see the white spots without zooming in to the right region. Maybe the solution is to zoom to the bounding box of the data and possibly adapt the colours to make things more visible. No worries if this does not get changed directly, I will send out for review, it works. Thanks

**Comment by chei90** [comment]
Hi @andreakoelzsch , 
it took long to respond, because of vacation and other things to do. With v1.2.0 the map should center on the data. 
Best regards, Christoph

**Comment by andreakoelzsch** [comment]
Hi Christoph, danke! Hab die neue App Version bauen können. Gern testen. VG Andrea



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Christoph Eichler ***@***.***>
Datum: 08.08.23 14:42 (GMT+01:00)
An: chei90/EMAC_Corridors ***@***.***>
Cc: "Koelzsch, Andrea" ***@***.***>, Author ***@***.***>
Betreff: Re: [chei90/EMAC_Corridors] html file is empty (Issue #2)


Hi Andrea,
it took long to respond, because of vacation and other things to do. With v1.2.0 the map should center on the data.
Best regards, Christoph
