### ISSUE TITLE
make a zip file containg all shapefile files

### ISSUE THREAD

**Issue by annescharf** [chei90/EMAC_Corridors#3]
Hi @chei90, together with Andrea I'm also checking the apps before sending them out to review. I think it would be nice, i.e. easier for the user, if all files of the shp are zipped into one artifact. The way to do that is to create a temporary directory were all the files are put in, this temporary directory is then zipped and given out as a artifact. It has to be a temporary directory, because currently anartifact cannot be a folder.
Unfortunately I do not know how to do this in Phyton, but in case you know R, [here](https://github.com/movestore/Template_R_Function_App/blob/master/developer_README.md#example-for-zipping) is an instruction how to do this in R, and [here](https://github.com/vee-jain/WeeklyKDE-MoveApps/blob/main/RFunction.R) (~L65, ~L230-234) an example within a R app.
This does not have high priority, but it would be nice to have it as some point. Thanks

**Comment by chei90** [comment]
Hi @annescharf, I've implemented this with v1.2.0. Best regards, Christoph
